// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcpBgYYDK9IwuVrYby13rA4n_WX2p_EYg',
    appId: '1:975363037783:web:cdd07f3d3323fdb9db2112',
    messagingSenderId: '975363037783',
    projectId: 'eventra-fae1f',
    authDomain: 'eventra-fae1f.firebaseapp.com',
    storageBucket: 'eventra-fae1f.firebasestorage.app',
    measurementId: 'G-9VZW0SK17Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvNUeZK61UHv-BY7JBiRyCLcolifI-0t8',
    appId: '1:975363037783:android:f26b7544c1db49eddb2112',
    messagingSenderId: '975363037783',
    projectId: 'eventra-fae1f',
    storageBucket: 'eventra-fae1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9-eb1mRW2jIRzBhdSdKJi0OpRZC_XFow',
    appId: '1:975363037783:ios:41db7e573d5bde68db2112',
    messagingSenderId: '975363037783',
    projectId: 'eventra-fae1f',
    storageBucket: 'eventra-fae1f.firebasestorage.app',
    iosBundleId: 'com.example.eventra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9-eb1mRW2jIRzBhdSdKJi0OpRZC_XFow',
    appId: '1:975363037783:ios:41db7e573d5bde68db2112',
    messagingSenderId: '975363037783',
    projectId: 'eventra-fae1f',
    storageBucket: 'eventra-fae1f.firebasestorage.app',
    iosBundleId: 'com.example.eventra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcpBgYYDK9IwuVrYby13rA4n_WX2p_EYg',
    appId: '1:975363037783:web:a6253e556b1a20c9db2112',
    messagingSenderId: '975363037783',
    projectId: 'eventra-fae1f',
    authDomain: 'eventra-fae1f.firebaseapp.com',
    storageBucket: 'eventra-fae1f.firebasestorage.app',
    measurementId: 'G-2CND5MN8VS',
  );
}
