// word_bank.dart
const List<String> wordBank = [
  "APPLE", "ORANGE", "BANANA", "GRAPE", "MANGO", "PINEAPPLE", "PEACH", "PEAR", "CHERRY", "PLUM",
  "STRAWBERRY", "BLUEBERRY", "KIWI", "LEMON", "LIME", "APRICOT", "PAPAYA", "WATERMELON", "FIG",
  "GUAVA", "COCONUT", "MELON", "DATE", "AVOCADO", "BLACKBERRY", "CRANBERRY", "DRAGONFRUIT", "ELDERBERRY", "GRAPEFRUIT", "HONEYDEW",
  "JACKFRUIT", "KUMQUAT", "LYCHEE", "MANDARIN", "NECTARINE", "OLIVE", "PASSIONFRUIT", "QUINCE", "RASPBERRY", "STARFRUIT",
  "TANGERINE", "UGLI", "VOAVANGA", "WALNUT", "XIGUA", "YUZU", "ZUCCHINI", "BROCCOLI", "CARROT",
  "CUCUMBER", "EGGPLANT", "LETTUCE", "MUSHROOM", "ONION", "PEPPER", "POTATO", "PUMPKIN", "RADISH",
  "SPINACH", "TOMATO", "TURNIP", "ZUCCHINI", "ASPARAGUS", "BEET", "CABBAGE", "CAULIFLOWER", "CELERY", "CORN",
  "GARLIC", "GINGER", "KALE", "OKRA", "PARSNIP", "PEA", "SQUASH", "SWEDE", "YAM", "ARTICHOKE", "BASIL",
  "CILANTRO", "CHIVE", "DILL", "FENNEL", "MINT", "OREGANO", "PARSLEY", "ROSEMARY", "SAGE", "THYME",
  "VANILLA", "ALMOND", "CASHEW", "CHESTNUT", "HAZELNUT", "PEANUT", "PISTACHIO", "PECAN", "MACADAMIA"
];
